# Generated by Django 4.1.2 on 2022-10-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhotoUser",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.TextField(max_length=200)),
            ],
        ),
    ]
